In [1]:
import pandas as pd
import numpy as np

Command1: zcat MUTATIONS.csv.gz | awk -F',' 'NR>1{genes[$1] = genes[$1] "," $2} END {for (sample in genes) print sample","substr(genes[sample], 2)}' > TempMutations.csv <br>

Command2: 

Command2:zcat MUTATIONS.csv.gz | awk -F',' '{ if (NF > max_fields) max_fields = NF } END { print max_fields }'


Command2: zcat MUTATIONS.
csv.gz | cut -d ',' -f 2 | tail -n +2 | sort | uniq > genes.txt


-------------
zcat DST_MEASUREMENTS.csv.gz | grep "LEV" | grep "CRyPTIC" > DST_LEV.csv


----------------
cat DST_LEV.csv | awk -F "," '{print $1}' | uniq  > SAMPLEID.csv

----------------
DATAMATRIX_LEV.csv has 11,183 samples
Maximum number of mutated genes in a sample 1544. This is lower than the total number of genes which is around 3862

IN DST_measurement for LEV with CRyPTIC consortium dataset = 15,224 samples <br>
for LEV alone there were around 20,668 samples <br>
using LEV + CRyPTIC dataset <br>

In [2]:
genelist = pd.read_csv("genes.txt", header = None)

In [3]:
genelist.head()

         0
0  35kd_ag
1      PE1
2     PE12
3     PE13
4     PE14

In [4]:
genelist.size

3862

In [5]:
Max_fields = 1544
Mutations_list = pd.read_csv("DATAMATRIX_LEV.csv", header = None, names = range(Max_fields))

C:\Users\vinay\AppData\Local\Temp\ipykernel_26084\761361708.py:2: DtypeWarning: Columns (1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543) have mixed types. Specify dtype option on import or set low_memory=False.
  Mutations_list = pd.read_csv("DATAMATRIX_LEV.csv", header = None, names = range(Max_fields))

In [6]:
Mutations_list.head()

,0,1,2,3,4,5,6,7,8,9,...,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543
0,site.05.subj.CA-0446.lab.CO-07847-19.iso.1,PE1,PE2,PE3,PE35,PE8,PE_PGRS1,PE_PGRS22,PE_PGRS27,PE_PGRS32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,site.03.subj.GB-83750038.lab.83750038.iso.1,PE1,PE12,PE3,PE35,PE8,PE_PGRS31,PE_PGRS32,PE_PGRS38,PE_PGRS42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,site.06.subj.SGD_0014-14.lab.06MIL0081.iso.1,PE1,PE16,PE27,PE3,PE35,PE4,PE6,PE8,PE_PGRS1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,site.05.subj.LS-0833.lab.LS-10414-18.iso.1,PE1,PE15,PE18,PE26,PE27,PE3,PE35,PE8,PE_PGRS16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,site.20.subj.SCH7887477.lab.YA00134140.iso.1,PE1,PE2,PE26,PE3,PE35,PE8,PE_PGRS1,PE_PGRS14,PE_PGRS32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
Mutations_list.head()

,0,1,2,3,4,5,6,7,8,9,...,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543
0,site.05.subj.CA-0446.lab.CO-07847-19.iso.1,PE1,PE2,PE3,PE35,PE8,PE_PGRS1,PE_PGRS22,PE_PGRS27,PE_PGRS32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,site.03.subj.GB-83750038.lab.83750038.iso.1,PE1,PE12,PE3,PE35,PE8,PE_PGRS31,PE_PGRS32,PE_PGRS38,PE_PGRS42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,site.06.subj.SGD_0014-14.lab.06MIL0081.iso.1,PE1,PE16,PE27,PE3,PE35,PE4,PE6,PE8,PE_PGRS1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,site.05.subj.LS-0833.lab.LS-10414-18.iso.1,PE1,PE15,PE18,PE26,PE27,PE3,PE35,PE8,PE_PGRS16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,site.20.subj.SCH7887477.lab.YA00134140.iso.1,PE1,PE2,PE26,PE3,PE35,PE8,PE_PGRS1,PE_PGRS14,PE_PGRS32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
def mut2datarray(df, gene_list):
    df_output = pd.DataFrame(columns = gene_list)
    for ind_row, row in df.iterrows():
        df_output.loc[ind_row] = [1 if gene in row.values else 0 for gene in gene_list]
#        for ind_gene, gene in enumerate(gene_list):
#            dataarray[ind_row,ind_gene] = 1 if gene in df.iloc[ind_row,:] else 0
    return df_output

In [8]:
def mut2datarray(df, gene_list):
    dataarray = []
    for _, row in df.iterrows():
        gene_presence = [1 if gene in row.values else 0 for gene in gene_list]
        dataarray.append(gene_presence)
    return dataarray

In [27]:
Mutations_list.iloc[0:3,:]

,0,1,2,3,4,5,6,7,8,9,...,15214,15215,15216,15217,15218,15219,15220,15221,15222,15223
0,site.05.subj.CA-0446.lab.CO-07847-19.iso.1,PE1,PE2,PE3,PE35,PE8,PE_PGRS1,PE_PGRS22,PE_PGRS27,PE_PGRS32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,site.03.subj.GB-83750038.lab.83750038.iso.1,PE1,PE12,PE3,PE35,PE8,PE_PGRS31,PE_PGRS32,PE_PGRS38,PE_PGRS42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,site.06.subj.SGD_0014-14.lab.06MIL0081.iso.1,PE1,PE16,PE27,PE3,PE35,PE4,PE6,PE8,PE_PGRS1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_LEV = mut2datarray(Mutations_list, genelist[0])

KeyboardInterrupt:

In [14]:
mutarray.head()

,35kd_ag,PE1,PE12,PE13,PE14,PE15,PE16,PE17,PE18,PE19,...,yrbE1B,yrbE2A,yrbE3A,yrbE3B,yrbE4A,yrbE4B,zmp1,zur,zwf1,zwf2
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,1,0,0,1,0,0